### ISSUE TITLE
 Illegal PlayerChunkMap::addEntity for world End

### ISSUE THREAD

**Issue by ehetteNandaYo** [Esmorall/EntityTrackerFixer#12]
I'm getting this in the end, any ideas ?

paper-161

```
[04:42:10] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world End: EntityComplexPart['Ender Dragon'/255944, uuid='d81fe779-d84a-4d5e-ba46-8696469a1382', l='End', x=-4.58, y=64.66, z=1.52, cx=0, cz=0, tl=0, v=false, d=false]
[04:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
[04:42:10] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
[04:42:10] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:42:10] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:42:10] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[04:42:10] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[04:42:10] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[04:42:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[04:42:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[04:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
[04:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[04:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[04:42:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[04:42:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by metalshark** [comment]
Snap on paper-162:

```
java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world Australia: EntityArmorStand['Armor Stand'/78912, uuid='6aabba64-6b89-4492-b7d3-56c339a42504', l='Australia', x=-4534.58, y=60.58, z=-993.21, cx=-284, cz=-63, tl=0, v=false, d=false]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1490)
at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185)
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by fredagsguf** [comment]
Happening for me aswell.

**Comment by HexedHero** [comment]
Fixed https://github.com/Esmorall/EntityTrackerFixer/pull/11
