### ISSUE TITLE
Ender Dragon Console Spam

### ISSUE THREAD

**Issue by Rage-GitHub** [Esmorall/EntityTrackerFixer#14]
I'm getting this error when players are near or engaging the Ender Dragon. It only happens when it's alive but it constantly spams this error until the Dragon is killed. 

### ETF Version
1.2.2
### PaperSpigot Version
Paper version git-Paper-201 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

```[21:05:14 WARN]: at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1564)
[21:05:14 WARN]: at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
[21:05:14 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:05:14 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[21:05:14 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[21:05:14 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[21:05:14 WARN]: at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[21:05:14 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[21:05:14 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[21:05:14 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1234)
[21:05:14 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[21:05:14 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1152)
[21:05:14 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[21:05:14 WARN]: at java.lang.Thread.run(Thread.java:748)
[21:05:14 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/945, uuid='0ef58c98-6c25-4759-ac7f-bea04ec90feb', l='world_the_end', x=14.12, y=71.87, z=-1.15, cx=0, cz=0, tl=0, v=false, d=false]```

**Comment by Elric02** [comment]
Exact same problem on same version, please do something ^^

**Comment by Elecast2** [comment]
Fixed on latest version
