### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by TheKlimoT** [Esmorall/EntityTrackerFixer#15]
`
[16:27:47 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityEnderman['Enderman'/867343, uuid='bf956b7c-c13a-42de-a23d-12640476f4d1', l='world', x=4782.50, y=66.00, z=-524.50, cx=298, cz=-33, tl=235, v=false, d=true]
[16:27:47 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1549)
[16:27:47 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
[16:27:47 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:27:47 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:27:47 WARN]:        at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[16:27:47 WARN]:        at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[16:27:47 WARN]:        at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[16:27:47 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:27:47 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[16:27:47 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1200)
[16:27:47 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[16:27:47 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1127)
[16:27:47 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:935)
[16:27:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[`

**Comment by Elecast2** [comment]
fixed on latest version
