### ISSUE TITLE
Spam in console, please answer: Illegal PlayerChunkMap

### ISSUE THREAD

**Issue by xMrEnderman** [Esmorall/EntityTrackerFixer#16]
Hey! In my console is a spam:
[11:46:36] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityPigZombie['Zombie Pigman'/29666, uuid='ccfb887b-2931-475e-90f5-2401c10f506b', l='world', x=1861.50, y=64.00, z=-1222.50, cx=116, cz=-77, tl=2881, v=false, d=true]
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1806)
[11:46:36] [Server thread/WARN]:     at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[11:46:36] [Server thread/WARN]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:46:36] [Server thread/WARN]:     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[11:46:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[11:46:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958)
[11:46:36] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
[11:46:36] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityPigZombie['Zombie Pigman'/29020, uuid='956c3b10-d23c-4ce9-9305-00e024663b68', l='world', x=1861.50, y=64.00, z=-1223.50, cx=116, cz=-77, tl=8329, v=false, d=true]
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1806)
[11:46:36] [Server thread/WARN]:     at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
[11:46:36] [Server thread/WARN]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:46:36] [Server thread/WARN]:     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[11:46:36] [Server thread/WARN]:     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[11:46:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[11:46:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169)
[11:46:36] [Server thread/WARN]:     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958)
[11:46:36] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)

Can you please solve it? The spam won't end ;(
I have spigot build 261 and the newest version of plugin.

**Comment by adamromulus** [comment]
Also have this issue, it will happen with any mob. 

I switched to the preview release he has here. I'd recommend it as it fixed a few other issues, crossing my fingers it fixes this as well. 
https://github.com/Esmorall/EntityTrackerFixer/pull/11

**Comment by stonegray** [comment]
Also have this issue, occurs with ender dragon

**Comment by Elecast2** [comment]
Fixed on latest version
