### ISSUE TITLE
Spigot 1.16.2 incompatible

### ISSUE THREAD

**Issue by Blueeyestar** [Esmorall/EntityTrackerFixer#19]
A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake. Welcome to the sleepless nights :)

`[00:12:34] [Server thread/INFO]: [EntityTrackerFixer] Setting disable tick for untracked to: false
[00:12:34] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minemora.entitytrackerfixer.v1_16_R2.NMSHandler
[00:12:34] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[00:12:34] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:12:34] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:12:34] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[00:12:34] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[00:12:34] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.nms.NMSCheck.getNMS(NMSCheck.java:14)
[00:12:34] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.EntityTrackerFixer.onEnable(EntityTrackerFixer.java:25)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[00:12:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[00:12:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[00:12:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[00:12:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[00:12:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[00:12:34] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:12:34] [Server thread/ERROR]: [EntityTrackerFixer] Could not find support for this Spigot version.
[00:12:34] [Server thread/ERROR]: Error occurred while enabling EntityTrackerFixer v1.3.1 (Is it up to date?)
java.lang.NullPointerException: null
	at net.minemora.entitytrackerfixer.EntityTrackerFixer.onEnable(EntityTrackerFixer.java:26) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

https://pastebin.com/hky6vU1Z

**Comment by RgtArRr** [comment]
In order of word by md_5 " it does contain a reasonable amount of internal changes", that means the same NMS can be copypaste using the v1_16_R1. right?

**Comment by RgtArRr** [comment]
I try it, and apparently it works.

**Comment by JhordanPG** [comment]
I also have a 1.16.2 server and the plugin doesn't work for me.

**Comment by RgtArRr** [comment]
Because this plugin is using NSM, if u wanna for 1.16.2 for now you need to compile and fixed be yourself
