### ISSUE TITLE
the Update to Spigo 1.17 has been released

### ISSUE THREAD

**Issue by CloudeLecaw** [Esmorall/EntityTrackerFixer#28]
and with it a little issue onstartup 

```
[08:35:49] [Server thread/INFO]: [EntityTrackerFixer] Setting disable tick for untracked to: true
[08:35:49] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minemora.entitytrackerfixer.v1_17_R1.NMSHandler
[08:35:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[08:35:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[08:35:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:35:49] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[08:35:49] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.nms.NMSCheck.getNMS(NMSCheck.java:14)
[08:35:49] [Server thread/WARN]: 	at net.minemora.entitytrackerfixer.EntityTrackerFixer.onEnable(EntityTrackerFixer.java:25)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[08:35:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[08:35:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[08:35:49] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[08:35:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[08:35:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[08:35:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[08:35:49] [Server thread/ERROR]: [EntityTrackerFixer] Could not find support for this Spigot version.
[08:35:49] [Server thread/ERROR]: Error occurred while enabling EntityTrackerFixer v1.3.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.minemora.entitytrackerfixer.nms.NMS.startUntrackerTask(org.bukkit.plugin.Plugin)" because "this.nms" is null
	at net.minemora.entitytrackerfixer.EntityTrackerFixer.onEnable(EntityTrackerFixer.java:26) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by cascaseno** [comment]
As long as it is not officially updated, you can use the updated version that I made.
I've tried it and it works fine, but if you find any bugs let me know.
Pull request: https://github.com/Elecast2/EntityTrackerFixer/pull/30

**Comment by CloudeLecaw** [comment]
Closed because its no longer needed
