### ISSUE TITLE
Console spam (EntityTrackerFixer v1.1 generated an exception while executing task 12)

### ISSUE THREAD

**Issue by Busted11290** [Esmorall/EntityTrackerFixer#4]
Updated Paper to latest build from tonight, console is then spammed with this.

**Server:** Paper-194
**Version:** 1.14.4
**Plugin Version:** 1.1

https://pastebin.com/mCaVYGK3

**Comment by successed** [comment]
`[17:36:23 WARN]: [EntityTrackerFixer] Plugin EntityTrackerFixer v1.1 generated an exception while executing task 98294
java.lang.IllegalStateException: Asynchronous getNearbyEntities!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-194]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.getNearbyEntities(CraftEntity.java:531) ~[patched_1.14.4.jar:git-Paper-194]
        at net.minemora.entitytrackerfixer.CheckTask.checkWorld(CheckTask.java:40) ~[?:?]
        at net.minemora.entitytrackerfixer.CheckTask.run(CheckTask.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-194]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-194]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-194]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
`

**Comment by ArtelGG** [comment]
Update to the [latest release](https://www.spigotmc.org/resources/70902/).
