### ISSUE TITLE
New NPE

### ISSUE THREAD

**Issue by HexedHero** [Esmorall/EntityTrackerFixer#9]
`
[10:31:03 WARN]: [EntityTrackerFixer] Task #27 for EntityTrackerFixer v1.2.2 generated an exception
java.lang.NullPointerException: null
at net.minemora.entitytrackerfixer.v1_15_R1.entityTick.EntityTickManager.disableTicking(EntityTickManager.java:43) ~[?:?]
at net.minemora.entitytrackerfixer.v1_15_R1.tasks.UntrackerTask.untrackProcess(UntrackerTask.java:95) ~[?:?]
at net.minemora.entitytrackerfixer.v1_15_R1.tasks.UntrackerTask.run(UntrackerTask.java:44) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-80]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-80]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-80]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-80]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-80]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-80]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

Using the new untick setting

**Comment by Elecast2** [comment]
New experimental option was reworked on latest versions and this error shouldn't appear anymore
